[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "channel"
path = "src/channel.rs"

[[bin]]
name = "mutex"
path = "src/mutex.rs"

[[bin]]
name = "condvar"
path = "src/condvar.rs"
